---
title: "coexpression-eqtls"
author: "em"
date: "December 27, 2019"
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('~/Documents/capsella-eqtl/')
library(dplyr)

```

### Make Gemma Input files

Bim and bam files
```{bash, eval=F}
##scaf1_8.tags.map and scaf1_8.tags.ped generated by YWL
gunzip ../data/gemma/scaf1_8.tags.ped.gz
plink --noweb --file ../data/gemma/scaf1_8.tags --keep ../data/gemma/146_DNA_names_forplink --recode --out ../data/gemma/tags146 
plink --noweb --file ../data/gemma/tags146 --make-bed --out ../data/gemma/tags146 

```




Make the fam file for gemma:
```{r}
tfam = read.table('data/gemma-files/t146.fam', stringsAsFactors = F)

inlist = read.table('data/id-list', stringsAsFactors = F, header=T)

#stick fam names onto the normalized iegenvectors
namemerge = dplyr::left_join(nEigens, namecol, by="DNA_short.name")
allmerge = dplyr::left_join(myfam, namemerge, by = c('V2' = "DNA_vcfname"))

newfam = allmerge[,c(1:5, 31:45)]
write.table(newfam, file = 'data/tags146.fam', row.names=F, col.names=F, quote=F)



```

Run gemma on the hpcc.
```{bash, eval=F}

cd /mnt/home/josep993/trans-eQTL/data/gemma/batched-tags/
~/Apps/gemma-0.98.1-linux-static -bfile tags146 -k -gk 2 -o tags146
mv output/t146.sXX.txt .
~/Apps/gemma-0.98.1-linux-static -bfile tags146 -k tags146.sXX.txt -lmm 2 -n $SLURM_ARRAY_TASK_ID -maf 0.05 -o tb.$SLURM_ARRAY_TASK_ID
Rscript --vanilla parse-gemma-output.R output/tb.${SLURM_ARRAY_TASK_ID}.assoc.txt tb.${SLURM_ARRAY_TASK_ID}.tophits
```


Here is the rcode for parse-gemma-output.R
```{r, eval=F}
args = commandArgs(trailingOnly=TRUE)


myresults = read.table(args[1], header=T, stringsAsFactors=F)

myresults$fdr = p.adjust(myresults$p_lrt, method="fdr")
sigresults = myresults[myresults$fdr < 0.25,]
write.table(sigresults, file = args[2], row.names=F, quote=F)
```

```{bash, eval=F, echo=F}
rsync -ave ssh josep993@rsync.hpcc.msu.edu:trans-eQTL/data/gemma/batched-tags/*tophits data/gemma-files/

```

Look at the results
```{r}
#system('head -n 1 data/gemma-files/tb.4.tophits > data/gemma-files/tb.allhits')
#system("awk 'FNR > 1' data/gemma-files/*tophits >> data/gemma-files/tb.allhits")

allhits = read.table('data/gemma-files/tb.allhits', header=T, stringsAsFactors = F)
sighits = dplyr::filter(allhits, fdr < 0.1)
sighits
```


Where are the sighits?



Are any of them also in the all-by-all analysis?
